version: 2
jobs:
  build:
    # Needs to match repository name; when the role is included normally, it will be `gsa.jenkins`. Also, needs to be an absolute path due to
    # https://circleci.com/docs/2.0/local-jobs/#relative-path-for-working_directory
    working_directory: /etc/jenkins-deploy
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packages
          command: apk add --update-cache ansible git make
      - run:
          name: Start remote container
          command: make start_container
      - run:
          name: Install Ansible roles
          command: make install_roles
      - run:
          name: Run Ansible playbook
          command: make test_ci

  ansible_test:
    docker:
      - image: circleci/python:3.6
    environment:
      PIPENV_VENV_IN_PROJECT: 1
    working_dir: ~/jenkins-deploy
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-pipenv-{{ checksum "Pipfile.lock" }}
            - v1-pipenv-
      - run: pipenv sync --dev
      - save_cache:
          key: v1-pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run: pipenv run test

  validate_terraform:
    working_directory: /etc/jenkins-deploy
    docker:
      - image: hashicorp/terraform
    steps:
      - checkout
      - run:
          name: Install Make
          command: apk add --update make
      - run:
          name: Set up Terraform
          command: make terraform_init
      - run:
          name: Check Terraform syntax
          command: make validate_terraform


workflows:
  version: 2
  build_and_test:
    jobs:
      - ansible_test
      - build
      - validate_terraform
