---
dependency:
  name: galaxy
  options:
    role-file: tests/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  # TODO fix linting errors and enable
  enabled: false
platforms:
  - name: centos
    image: centos:7
#  - name: xenial
#    image: ubuntu:xenial
#  - name: bionic
#    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    # TODO fix linting errors and enable
    enabled: false
verifier:
  name: testinfra
  lint:
    name: flake8
